language: go

go:
  - 1.8.x
  - 1.x

arch:
  - amd64
  - ppc64le

before_install:
  - go get -t -v ./...
  - go get -t -v github.com/modern-go/reflect2-tests/...

script:
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
